---
role:
  install:
    - |
      if [ ! -d "$HOME/storage" ]; then
        termux-setup-storage
      fi
  # dir: .termux
  link:
    - ".termux/*:.termux"
  post_install:
    - "find ~/.tmux/plugins/* ! -path '*.git*' -type f -exec termux-fix-shebang '{}' \\;"
  # -name '*.sh'
