---
role:
  # pkg:
  #   - termux-exec
  #   - proot
  install:
    - command: termux-setup-storage
      if: '[ ! -d "$HOME/storage" ]'
  # dir: .termux
  link:
    - ".termux/*:.termux"
  post_install:
    - "find ~/.tmux/plugins/* ! -path '*.git*' -type f -exec termux-fix-shebang '{}' \\;"
  # -name '*.sh'
